### ISSUE TITLE
Create new whiteboard error on localhost

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arijit11das/online-whiteboard#1]
```
What steps will reproduce the problem?
1. deploy project use 
  java -jar whiteboard-streaming.war
2. visit 
   http://localhost:8080/whiteboard/create/ 
3. click "Create and start Drawing!"
   got follow error information, how to fix it?
thanks.

2011/09/26 18:00:14 com.sun.faces.lifecycle.ProcessValidationsPhase execute
警告: java.net.ConnectException: Connection timed out: connect
javax.faces.FacesException: java.net.ConnectException: Connection timed out: con
nect
        at org.primefaces.component.captcha.Captcha.validateValue(Captcha.java:1
72)
        at javax.faces.component.UIInput.validate(UIInput.java:967)
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1233)
        at javax.faces.component.UIInput.processValidators(UIInput.java:698)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIForm.processValidators(UIForm.java:253)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:11
72)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValida
tionsPhase.java:76)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)

        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534
)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:476)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:517)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:934)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
404)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:869)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:117)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:285)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:116)
        at com.ocpsoft.pretty.PrettyFilter.doFilter(PrettyFilter.java:110)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1323)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:474)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:517)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:934)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
404)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:869)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:117)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(Cont
extHandlerCollection.java:247)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerColl
ection.java:151)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:346)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.
java:581)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpCo
nnection.java:1057)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:807)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)

        at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:41
1)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEn
dPoint.java:526)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEnd
Point.java:41)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:528)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at java.net.Socket.connect(Socket.java:478)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:394)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:233)
        at sun.net.www.http.HttpClient.New(HttpClient.java:306)
        at sun.net.www.http.HttpClient.New(HttpClient.java:323)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLC
onnection.java:970)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:911)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
.java:836)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLCo
nnection.java:1014)
        at org.primefaces.component.captcha.Captcha.validateValue(Captcha.java:1
63)
        ... 53 more
2011/09/26 18:01:22 com.sun.faces.lifecycle.ProcessValidationsPhase execute
警告: java.net.ConnectException: Connection timed out: connect
javax.faces.FacesException: java.net.ConnectException: Connection timed out: con
nect
        at org.primefaces.component.captcha.Captcha.validateValue(Captcha.java:1
72)
        at javax.faces.component.UIInput.validate(UIInput.java:967)
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1233)
        at javax.faces.component.UIInput.processValidators(UIInput.java:698)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIForm.processValidators(UIForm.java:253)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBa
se.java:1214)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:11
72)
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValida
tionsPhase.java:76)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)

        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534
)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:476)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:517)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:934)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
404)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:869)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:117)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:285)
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:116)
        at com.ocpsoft.pretty.PrettyFilter.doFilter(PrettyFilter.java:110)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1323)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:474)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:517)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:934)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
404)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:869)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:117)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(Cont
extHandlerCollection.java:247)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerColl
ection.java:151)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:346)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.
java:581)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpCo
nnection.java:1057)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:807)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)

        at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:41
1)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEn
dPoint.java:526)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEnd
Point.java:41)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:528)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)
        at java.net.Socket.connect(Socket.java:478)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:163)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:394)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:233)
        at sun.net.www.http.HttpClient.New(HttpClient.java:306)
        at sun.net.www.http.HttpClient.New(HttpClient.java:323)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLC
onnection.java:970)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:911)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
.java:836)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLCo
nnection.java:1014)
        at org.primefaces.component.captcha.Captcha.validateValue(Captcha.java:1
63)
        ... 53 more

```

Original issue reported on code.google.com by `liriche...@gmail.com` on 26 Sep 2011 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
The project is not supported anymore. You can check out and build it from 
source if you want http://code.google.com/p/online-whiteboard/source/checkout

By the way, issue you reported seems to be a temporary connection problem.
```

Original comment by `ovarak...@googlemail.com` on 29 Dec 2011 at 4:34
- Changed state: **WontFix**
